#SPDX-License-Identifier: MIT-0
---
# tasks file for front-end-logic
- name: Install frontend dependencies
  npm:
    path: "{{ frontend_dir }}"

- name: Build frontend
  shell: npm run build
  args:
    chdir: "{{ frontend_dir }}"

- name: Copy frontend build to nginx directory
  copy:
    src: "{{ frontend_dir }}/build/"
    dest: /var/www/html/
    owner: www-data
    group: www-data
    mode: "0755"
    remote_src: yes

- name: Configure Nginx
  copy:
    dest: /etc/nginx/sites-available/default
    content: |
      server {
          listen 80;
          root /var/www/html;
          index index.html;
          server_name _;

          location / {
              try_files $uri /index.html;
          }

          location /api/ {
              proxy_pass http://localhost:5000/;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection 'upgrade';
              proxy_set_header Host $host;
              proxy_cache_bypass $http_upgrade;
          }
      }

- name: Restart Nginx
  service:
    name: nginx
    state: restarted

- name: Start frontend with pm2
  command: pm2 start "npm start" --name frontend
  args:
    chdir: /vagrant/client