#SPDX-License-Identifier: MIT-0
---
# tasks file for setup_logic
- name: test connectivity
  ping:

- name: Update apt cache
  apt: update_cache=yes

- name: clone Github repo
  git :
    repo : "{{github_repo}}"
    dest: /vagrant/app
    version: main
    